config/routes.rb
Rails.application.routes.draw do
  root to: "lecons#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lecons, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lecon.rb
class Lecon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lecons_controller.rb
class LeconsController < ApplicationController
    def index
        @lecons = Lecon.all
    end

    def show
        @lecon = Lecon.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetMaman</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lecons/index.html.erb
<p>this is my index</p>

<ul>
  <% @lecons.each do |lecon| %>
    <li><%= link_to lecon.titre, lecon_path(lecon) %></li>
  <% end %>
</ul>

app/views/lecons/show.html.erb
<p>this is my show</p>

<p><%= @lecon.titre %>

<%= link_to "Toutes les leçons", lecons_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>